# Generated by Django 5.2.9 on 2025-12-13 18:56

import candidates.models
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "ballot_name",
                    models.CharField(
                        help_text="Name to appear on the record", max_length=255
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(validators=[candidates.models.validate_age]),
                ),
                ("nic", models.CharField(max_length=20, unique=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other / Prefer not to say"),
                        ],
                        default="OTHER",
                        max_length=10,
                    ),
                ),
                ("address", models.TextField()),
                (
                    "mailing_address",
                    models.TextField(
                        blank=True,
                        help_text="If different from the permanent address.",
                        null=True,
                    ),
                ),
                ("contact_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                (
                    "is_registered_voter",
                    models.BooleanField(
                        default=False,
                        help_text="Confirm that the candidate is a registered voter in the National Voter Registry.",
                    ),
                ),
                (
                    "electoral_district",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "polling_division",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "gn_division",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Gram Niladhari (GN) Division",
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        help_text="Serial number from the certified Electoral Register (e.g., Reg No: 154 in Unit A).",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "nomination_type",
                    models.CharField(
                        choices=[
                            ("PARTY", "Recognized Political Party"),
                            ("INDEPENDENT", "Independent Candidate"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "party_name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SLPP", "Sri Lanka Podujana Peramuna (SLPP)"),
                            ("SJB", "Samagi Jana Balawegaya (SJB)"),
                            ("NPP", "National People’s Power (NPP)"),
                            ("SLFP", "Sri Lanka Freedom Party (SLFP)"),
                            ("UNP", "United National Party (UNP)"),
                            ("MJP", "Mawbima Janatha Pakshaya (MJP)"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "party_secretary_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mp_status_proof",
                    models.FileField(blank=True, null=True, upload_to="mp_proofs/"),
                ),
                (
                    "nominator_nic",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "candidate_photo",
                    models.ImageField(
                        help_text="Passport-style colour photograph to be used on the ballot / voter information.",
                        upload_to="candidate_photos/",
                    ),
                ),
                ("form_a", models.FileField(upload_to="form_a/")),
                (
                    "asset_declaration",
                    models.FileField(upload_to="asset_declarations/"),
                ),
                ("eligibility_declaration", models.BooleanField(default=False)),
                ("submission_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
